version: "2.1"

services:
 minetest:
  image: buckaroobanzay/minetest:5.3.0-r5
  ports:
   - "30000:30000/udp"
  depends_on:
   - "postgres"
  volumes:
   - "./data/minetest:/data"
#   - "./data/minetest/debug.txt:/root/.minetest/debug.txt"
  working_dir: /data
  command: minetestserver --config /data/minetest.conf --world /data/world/ --quiet

 postgres:
  image: postgres:12.4
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "postgres-data:/var/lib/postgresql/data"

 mapcleaner:
  build: ..
  volumes:
   - "./data/minetest/world/areas.dat:/areas.dat"
  environment:
   PGHOST: postgres
   PGUSER: postgres
   PGDATABASE: postgres
   PGPASSWORD: enter
   PGPORT: 5432
   AREAS_FILE: /areas.dat
  restart: "no"

volumes:
  postgres-data: {}
